export const FETCH_LIST_ITEMS = 'FETCH_LIST_ITEMS';
export const LIST_ITEMS_SUCCESS = 'LIST_ITEMS_SUCCESS';
export const LIST_ITEMS_ERROR = 'LIST_ITEMS_ERROR';

export const START_CREATE_ITEM = 'START_CREATE_ITEM';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR';

export const START_EDIT_ITEM = 'START_EDIT_ITEM';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_ERROR = 'EDIT_ITEM_ERROR';

export const START_DELETE_ITEM = 'START_DELETE_ITEM';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

